apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleaning-db-deployment
spec:
  template:
    metadata:
      labels:
        app: cleaning-db
    spec:
      containers:
        - name: cleaning-db-container
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: cleaningadmin
            - name: POSTGRES_PASSWORD
              value: bestcleaning
            - name: POSTGRES_DB
              value: cleaning-db
          ports:
            - containerPort: 5432
  replicas: 1
  selector:
    matchLabels:
      app: cleaning-db
---
apiVersion: v1
kind: Service
metadata:
  name: cleaning-db-service
spec:
  ports:
    - port: 5438
      targetPort: 5432
  selector:
    app: cleaning-db
