apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleaning-app-deployment
spec:
  template:
    metadata:
      labels:
        app: cleaning-app
    spec:
      containers:
        - name: cleaning-app-container
          image: born2flex/cleaning:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://cleaning-db-service:5438/cleaning-db
            - name: SPRING_DATASOURCE_USERNAME
              value: cleaningadmin
            - name: SPRING_DATASOURCE_PASSWORD
              value: bestcleaning
            - name: ACTIVEMQ_ADMIN_URL
              value: tcp://cleaning-mq-service:61616
  replicas: 1
  selector:
    matchLabels:
      app: cleaning-app
---
apiVersion: v1
kind: Service
metadata:
  name: cleaning-app-service
spec:
  selector:
    app: cleaning-app
  ports:
    - port: 8088
      targetPort: 8080
      nodePort: 30003
  type: NodePort
