global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'cleaning_service'
    metrics_path: '/657377712365/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: "Cleaning Server"

  - job_name: 'cleaning_user_service'
    metrics_path: '/657377712365/prometheus'
    static_configs:
      - targets: ['host.docker.internal:1177']
        labels:
          application: "Cleaning User Server"

  - job_name: 'notification_service'
    metrics_path: '/657377712365/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: "Notification Server"
