@startuml
set separator none
title CommercialProposal

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("CleaningApplication.CleaningApplication_boundary", "CleaningApplication", $tags="") {
  Component(CleaningApplication.CleaningApplication.Utils, "Utils", $techn="Module", $descr="", $tags="", $link="")
  Component(CleaningApplication.CleaningApplication.CommercialProposal, "CommercialProposal", $techn="Module", $descr="", $tags="", $link="")
}

Rel(CleaningApplication.CleaningApplication.CommercialProposal, CleaningApplication.CleaningApplication.Utils, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml