@startuml
set separator none
title Notification

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("CleaningApplication.CleaningApplication_boundary", "CleaningApplication", $tags="") {
  Component(CleaningApplication.CleaningApplication.Notification, "Notification", $techn="Module", $descr="", $tags="", $link="")
  Component(CleaningApplication.CleaningApplication.User, "User", $techn="Module", $descr="", $tags="", $link="")
  Component(CleaningApplication.CleaningApplication.CommercialProposal, "CommercialProposal", $techn="Module", $descr="", $tags="", $link="")
  Component(CleaningApplication.CleaningApplication.Order, "Order", $techn="Module", $descr="", $tags="", $link="")
}

Rel(CleaningApplication.CleaningApplication.Order, CleaningApplication.CleaningApplication.User, "uses", $techn="", $tags="", $link="")
Rel(CleaningApplication.CleaningApplication.Order, CleaningApplication.CleaningApplication.CommercialProposal, "uses", $techn="", $tags="", $link="")
Rel(CleaningApplication.CleaningApplication.Notification, CleaningApplication.CleaningApplication.User, "listens to", $techn="", $tags="", $link="")
Rel(CleaningApplication.CleaningApplication.Notification, CleaningApplication.CleaningApplication.CommercialProposal, "listens to", $techn="", $tags="", $link="")
Rel(CleaningApplication.CleaningApplication.Notification, CleaningApplication.CleaningApplication.Order, "listens to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml